spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/moat_travel_db
spring.datasource.username=root
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.encoding=utf-8
spring.sql.init.mode=always

spring.servlet.multipart.max-file-size=5MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=okutsumasami@gmail.com
spring.mail.password=${App_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

stripe.api-key=${API_SK}
stripe.webhook-secret=whsec_28fdc053b7d65ef986f6e217c000f166bbef099c02289f6942639ec0efc22f3e